openapi: 3.0.3
info:
  title: CIBER MED - OpenAPI 1.0
  description: Esta es la documentacion para la api de ciber med en donde se especifican los campos para el crud y el uso de los endpoints
  contact:
    email: isaacfernando5351@gmail.com
  version: 1.0.0
servers:
  - url: https://ciber-med-api.herokuapp.com
  - url: http://localhost:4000
tags:
  - name: user
    description: registro e inicio de sesion de usuarios
  - name: products
    description: crud para productos
  - name: tag
    description: este campo muestra el tipo uso
  - name: tipo uso
    description: crud para tipo de uso
  - name: tipo consumo
    description: crud par tipo de consumo
  - name: hola
    description: hola
  - name: empresa
    description: crud para empresas
paths:
  /register:
    post:
      tags:
        - user
      summary: create a new user usuario
      requestBody:
        description: los campos a recibir son
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/register"
          application/xml:
            schema:
              $ref: "#/components/schemas/register"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/register"
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/status"
            application/xml:
              schema:
                $ref: "#/components/schemas/status"
        "400":
          description: Invalid ID supplied
        "404":
          description: not found
        "405":
          description: Validation exception

  /login:
    post:
      tags:
        - user
      summary: register a user
      requestBody:
        description: recibe los campos que va a llenar
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
          application/xml:
            schema:
              $ref: "#/components/schemas/User"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/User"
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
            application/xml:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Invalid ID supplied
        "404":
          description: Pet not found
        "405":
          description: Validation exception
      security:
        - petstore_auth:
            - write:pets
            - read:pets

  /user/app/{id}:
    put:
      tags:
        - user
      summary: Update user
      description: con este endpoint se puede actualizar la informacion del usuario
      operationId: updateUser
      parameters:
        - name: id
          in: path
          description: name that need to be deleted
          required: true
          schema:
            type: string
      requestBody:
        description: Update an existent user in the store
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/register"
          application/xml:
            schema:
              $ref: "#/components/schemas/register"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/register"
      responses:
        200:
          description: successful operation

    delete:
      tags:
        - user
      summary: Delete user
      description: this can delete a user
      parameters:
        - name: id
          in: path
          description: The id that needs to be deleted
          required: true
          schema:
            type: number
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/delete"
        "400":
          description: Invalid id supplied
        "404":
          description: User not found

  /view/tags-products:
    get:
      tags:
        - tag
      summary: peticion get
      responses:
        "200":
          description: operacion exitosa
        "400":
          description: fallo el proceso

  /products:
    post:
      tags:
        - products
      summary: create a new product
      requestBody:
        description: campos requeridos para el uso del crud de productos
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/products"
      responses:
        "200":
          description: operacion exitosa
        "400":
          description: operacion fallida
    get:
      tags:
        - products
      summary: read a products
      responses:
        "200":
          description: operation successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/status"
        "400":
          description: error

  /products/{id}:
    get:
      tags:
        - products
      summary: get a product
      parameters:
        - name: id
          in: path
          description: the id that needs to be a get products
          required: true
          schema:
            type: number
      responses:
        "200":
          description: this is a body request
        "400":
          description: error

    put:
      tags:
        - products
      summary: update a product
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: number
      requestBody:
        description: campos que puede alterar
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/products"
          application/xml:
            schema:
              $ref: "#/components/schemas/products"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/products"
      responses:
        "200":
          description: operation successful
        "400":
          description: operation failed

  /filter/{id}:
    get:
      tags:
        - products
      summary: obtener un producto filtrado por tipo de uso
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: number
      responses:
        "200":
          description: this is a body request
        "400":
          description: error

  /tipo_uso:
    post:
      tags:
        - tipo uso
      summary: create a new tipe use
      requestBody:
        description: campos requeridos para crear un nuevo tipo de uso
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/tipo_uso"
          application/xml:
            schema:
              $ref: "#/components/schemas/tipo_uso"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/tipo_uso"
      responses:
        "200":
          description: operacion exitosa
        "400":
          description: operacion fallida

    get:
      tags:
        - tipo uso
      summary: obtener lista de tipos de consumo
      responses:
        "200":
          description: operation successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/status"
        "400":
          description: error

  /tipo_uso/{id}:
    get:
      tags:
        - tipo uso
      summary: obtener un tipo de uso por su id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: number
      responses:
        "200":
          description: operation successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/status"
        "400":
          description: error

    put:
      tags:
        - tipo uso
      summary: update a product
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: number
      requestBody:
        description: campos requeridos para actualizar un tipo de uso
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/tipo_uso"
          application/xml:
            schema:
              $ref: "#/components/schemas/tipo_uso"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/tipo_uso"
      responses:
        "200":
          description: operacion exitosa
        "400":
          description: operacion fallida

    delete:
      tags:
        - tipo uso
      summary: delete a type of the use
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: number
      responses:
        "200":
          description: operacion exitosa
        "400":
          description: operacion fallida

  /tipo_consumo:
    get:
      tags:
        - tipo consumo
      summary: obtener la lista de tipos de consumo
      responses:
        "200":
          description: operation successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/status"
        "400":
          description: error

    post:
      tags:
        - tipo consumo
      summary: create a new product
      requestBody:
        description: campos requeridos para crear un tipo de consumo
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/tipo_consumo"
      responses:
        "200":
          description: operation successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/status"
        "400":
          description: error

  /tipo_consumo/{id}:
    get:
      tags:
        - tipo consumo
      summary: get a type of tipo consumo
      parameters:
        - name: id
          in: pat
          required: true
          schema:
            type: number
      responses:
        "200":
          description: operation successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/status"
        "400":
          description: error

  /hola/{id}:
    get:
      tags:
        - hola
      summary: este campo dice hola mundo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: number
      responses:
        '200':
          description: todo cool
        '400':
          description: error

  /empresa:
    get: 
      tags:
        - empresa
      summary: obtener la lista de las empresas que proveen los productos
      responses:
        "200":
          description: operation successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/empresa "
        "400":
          description: error
    
    post:
      tags:
        - empresa
      summary: crear una nueva empresa
      requestBody:
        description: campos requeridos
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/empresa"
      responses:
        "200":
          description: "operation succesfull"
          content:
            application/json:
              schema:
                $ref: "#"
        "400":
          description: error
    
  /empresa/{id}:
    delete:
      tags:
        - "empresa"
      summary: delete bussiness
      parameters: 
        - name: id
          in: path
          required: true
          schema:
            type: number
      responses:
        "200":
          description: operacion exitosa
        "400":
          description: operacion fallida
    put:
      tags:
        - "empresa"
      summary: update a bussiness
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: number
      responses:
        "200":
          description: operacion exitosa
        "400":
          description: operacion fallida

components:
  schemas:
    User:
      type: object
      properties:
        email:
          type: string
          example: patrick.jane@gmail.com
        contrasenia:
          type: string
          example: UserPatrick
      xml:
        name: user

    register:
      type: object
      properties:
        nombres:
          type: string
          example: Patrick
        apellidos:
          type: string
          example: Jane
        email:
          type: string
          example: patrick.jane@gmail.com
        contrasenia:
          type: string
          example: UserPatrick
      xml:
        name: register

    products:
      type: object
      properties:
        nombres:
          type: string
          example: Intestonomicina
        precios:
          type: string
          example: $0.15
        descripcion:
          type: string
          example: medicamento para dolores estomacales
        marca:
          type: string
          example: Laboratorios Lopez
        id_tipo_consumo:
          type: number
          example: 1
        id_tipo_uso:
          type: number
          example: 1
        cantidad_medicamento:
          type: number
          example: 200
        cant_gramos:
          type: string
          example: 500mg
      xml:
        name: products

    status:
      type: object
      properties:
        fieldCount:
          type: number
          example: 0
        affectedRows:
          type: number
          example: 1
        insertId:
          type: number
          example: 15
        info:
          type: string
          example: ""
        serverStatus:
          type: number
          example: 2
        warningStatus:
          type: number
          example: 0

    delete:
      type: object
      properties:
        fieldCount:
          type: number
          example: 0
        affectedRows:
          type: number
          example: 1
        insertId:
          type: number
          example: 0
        info:
          type: string
          example: ""
        serverStatus:
          type: number
          example: 2
        warningStatus:
          type: number
          example: 0
      xml:
        name: delete

    tipo_uso:
      type: object
      properties:
        tipo_uso:
          type: string
          example: oral
        estado:
          type: boolean
          example: 1
      xml:
        name: tipo_uso

    tipo_consumo:
      type: object
      properties:
        tipo_consumo:
          type: string
          example: oral
        estado:
          type: boolean
          example: 1
      xml:
        name: tipo_consumo

    hola:
      type: object
      properties:
        hola:
          type: string
          example: hola
        mundo:
          type: boolean
          example: 0
      xml:
        name: hola

    empresa:
      type: object
      properties:
        nombre_empresa:
           type: string
           example: lab ysk
        id_producto:
          type: integer
          example: 3
        direccion:
          type: string
          example:  sonsonate
        telefono:
          type: string
          example: +5032456-5665
        email: 
          type: string
          example: ysk@gmail.com
        lote: 
          type: integer
          example: 1
        activo:
          type: boolean
          example: 1
      xml: 
        name: empresa
  requestBodies:
    UserArray:
      description: List of user object
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/User"
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header
